### ISSUE TITLE
Missing Rigidbody on BlueSphere

### ISSUE THREAD

**Issue by ARTBankManager** [hfzhg/UnityRandomBlocks#1]
The blue sphere should has a rigidbody just as green and purple spheres do. Currently, once the blue sphere is clicked, the software will raise an exception at Sphere.cs line 29.

**Comment by hfzhg** [comment]
Thanks for reporting! We have added the missing rigidbody to blue sphere to avoid the crash at commit aff21c30b7797f62426041524ea0b61fba6c0f7c
