### ISSUE TITLE
Name mismatch for purple sphere stats in canvas

### ISSUE THREAD

**Issue by ARTBankManager** [hfzhg/UnityRandomBlocks#2]
There is a case mismatch for the label PurpleSpherestats in the canvas. The 's' in stats should be capitalized. Currently when the purple sphere is clicked, the script is trying to find the label but cannot due to the case mismatch. So it will raise an exception at line 33 of Sphere.cs

**Comment by hfzhg** [comment]
Thanks for reporting! We have fixed the typing error bug at commit aff21c30b7797f62426041524ea0b61fba6c0f7c
